# Generated by Django 2.0 on 2018-01-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180102_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='icon',
            field=models.CharField(choices=[('calendar', 'Calendar'), ('save', 'Save'), ('cube', 'Cube'), ('protest', 'Protest'), ('training', 'Training'), ('social', 'Social')], default='calendar', max_length=255),
        ),
    ]
